#Spring Boot server configuration
# Adresse du server : 0.0.0.0 -> toute addresse IP acceptée
server.address=0.0.0.0
# https://covoiturafpa-spring-api.herokuapp.com/
server.port=${PORT:8443}

spring.output.ansi.enabled=always 

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_schema=covoiturafpa

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/CovoiturAfpa?password=Afpa4apfA!&sslmode=require&user=afpaUser}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.ssl.enabled=false 
#server.ssl.key-store=classpath:covoiturafpa.jks
#server.ssl.key-store-type=pkcs12
#server.ssl.key-store-password=fgv60zs9egqj9n65aec37j
#server.ssl.key-alias=covoiturafpa

#logging.level.org.springframework.web: DEBUG

# Option à activer en production pour ne pas avoir les stacktrace dans les réponses serveur
# confi. disponibles : ALWAYS, NEVER
server.error.include-stacktrace=always

# Plus d'informations sur le paramètre de hCaptcha en environnement de dev
# https://docs.hcaptcha.com/#test-key-set-enterprise-account-bot-detected
hcaptcha.secret=0x6558B54dd6fb725f0bf6b418822a2aE3FE44C312
# Clef pour production ??? : 0x6558B54dd6fb725f0bf6b418822a2aE3FE44C312
hcaptcha.uri=https://hcaptcha.com/siteverify