#Spring Boot server configuration
server.address=localhost
server.port=8443

spring.output.ansi.enabled=always 

#H2 console web access configuration
#Open "http://0.0.0.0:8000/h2-console" and hit "Connect" button
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_schema=covoiturafpa

spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/CovoiturAFPA?currentSchema=covoiturafpa
spring.datasource.username=user
spring.datasource.password=usermdp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.ssl.enabled=true 
server.ssl.key-store=classpath:covoiturafpa.jks
server.ssl.key-store-type=pkcs12
server.ssl.key-store-password=fgv60zs9egqj9n65aec37j
server.ssl.key-alias=covoiturafpa

#./keytool.exe -genkey -keyalg RSA -alias covoiturafpa -keystore covoiturafpa.jks -storepass fgv60zs9egqj9n65aec37j -validity 365 -keysize 4096 -storetype pkcs12

# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: TRACE