#Spring Boot server configuration
server.address=0.0.0.0
server.port=5432

#H2 console web access configuration
#Open "http://0.0.0.0:8000/h2-console" and hit "Connect" button
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/CovoiturAFPA
spring.datasource.username=postgres
spring.datasource.password=mdproot 